name: salescheck
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  animated_snack_bar: ^0.4.0
  avatar_plus: ^0.0.5
  bottom_sheet: ^4.0.4
  cached_network_image: ^3.4.1
  country_code_picker: ^3.0.0
  d_chart: ^2.6.9
  datepicker_dropdown: ^0.1.5
  
  dotted_line: ^3.2.2
  drop_shadow: ^0.1.0
  dropdown_button2: ^2.3.9
  dynamic_height_grid_view: ^0.0.4
  easy_web_view: ^2.0.2
  fancy_password_field: ^2.0.7
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_file_downloader: ^2.0.0
  flutter_form_builder: ^9.3.0

  flutter_screenutil: ^5.9.3
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.10+1
  flutter_svg_provider: ^1.0.7
  flutter_widget_from_html: ^0.15.3
  google_fonts: ^6.2.1
  gradient_borders: ^1.0.1
  graphic: ^2.5.0
  htmltopdfwidgets: ^1.0.5
  http: ^1.2.2
  image_cropper: ^8.0.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  intl_phone_number_input: ^0.7.4
  path_provider: ^2.1.5
  pdf: ^3.11.1
  permission_handler: ^11.3.1
  share_plus: ^10.1.2
  shared_preferences: ^2.3.3
  skeletonizer: ^1.4.2
  syncfusion_flutter_pdfviewer: ^27.2.5
  toastification: ^2.3.0
  webcontent_converter: ^0.0.9+2
  webview_flutter: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  fonts:
        - family: geist
          fonts: 
          - asset: asset/fonts/geist/Geist-Regular.ttf
          - asset: asset/fonts/geist/Geist-Bold.ttf
            weight: 700
          - asset: asset/fonts/geist/Geist-SemiBold.ttf
            weight: 600
          - asset: asset/fonts/geist/Geist-Medium.ttf
            weight: 500
          - asset: asset/fonts/geist/Geist-Light.ttf
            weight: 300
          - asset: asset/fonts/geist/Geist-Thin.ttf
            weight: 100
          - asset: asset/fonts/geist/Geist-Black.ttf
            weight: 900
          - asset: asset/fonts/geist/Geist-ExtraBold.ttf
            weight: 800
          - asset: asset/fonts/geist/Geist-ExtraLight.ttf
            weight: 200
  assets:
  - .env
  - asset/background/
  - asset/banklogo/
  - asset/barang/
  - asset/detailorder/
  - asset/image/
  - asset/kelolaOutlet/
  - asset/pegawai/
  - asset/Pengaturan Pembayaran/
  - asset/promosi/
  - asset/qris/
  - asset/setting/
  - asset/settingAccount/
  - asset/struk/
  - asset/viewStruck/
  - asset/Rekening/
  - asset/buktipembayaran/

