name: salescheck
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  animated_snack_bar: ^0.4.0
  avatar_plus: ^0.0.5
  bottom_sheet: ^4.0.4
  country_code_picker: ^3.0.0
  d_chart: ^2.6.9
  datepicker_dropdown: ^0.1.5
  
  dotted_line: ^3.2.2
  drop_shadow: ^0.1.0
  dropdown_button2: ^2.3.9
  dynamic_height_grid_view: ^0.0.4
  fancy_password_field: ^2.0.7
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.3.0
  flutter_screenutil: ^5.9.3
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.10+1
  flutter_svg_provider: ^1.0.7
  google_fonts: ^6.2.1
  gradient_borders: ^1.0.1
  graphic: ^2.5.0
  image_cropper: ^8.0.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  intl_phone_number_input: ^0.7.4
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  toastification: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  fonts:
        - family: geist
          fonts: 
          - asset: asset/fonts/geist/Geist-Regular.ttf
          - asset: asset/fonts/geist/Geist-Bold.ttf
            weight: 700
          - asset: asset/fonts/geist/Geist-SemiBold.ttf
            weight: 600
          - asset: asset/fonts/geist/Geist-Medium.ttf
            weight: 500
          - asset: asset/fonts/geist/Geist-Light.ttf
            weight: 300
          - asset: asset/fonts/geist/Geist-Thin.ttf
            weight: 100
          - asset: asset/fonts/geist/Geist-Black.ttf
            weight: 900
          - asset: asset/fonts/geist/Geist-ExtraBold.ttf
            weight: 800
          - asset: asset/fonts/geist/Geist-ExtraLight.ttf
            weight: 200
  assets:
  - asset/background/Bgsplash.svg
  - asset/background/Bgform.svg
  - asset/background/Bgform.png
  - asset/image/arrow-down.svg
  - asset/image/Layer 2.svg
  - asset/image/tabler-icon-cash-banknote.svg
  - asset/image/tabler-icon-clipboard-text.svg
  - asset/image/tabler-icon-list-check.svg
  - asset/image/tabler-icon-square-rounded-plus-filled.svg
  - asset/image/tabler-icon-transition-bottom.svg
  - asset/image/tabler-icon-building-warehouse.svg
  - asset/image/galeryView.svg
  - asset/image/profile.svg
  - asset/image/edit-2.svg
  - asset/image/trash.svg
  - asset/image/apple.svg
  - asset/qris/qris.png
  - asset/banklogo/bca.png
  - asset/banklogo/bri.png
  - asset/banklogo/mandiri.png
  - asset/barang/Rectangle 894.png
  - asset/image/celocelo.svg
  - asset/background/Splashscreen.svg
  - asset/background/BgBoarding.png
  - asset/background/BgformNew.svg
  - asset/image/beranda.svg
  - asset/image/pengaturan.svg
  - asset/image/transaksi.svg
  - asset/image/box.svg
  - asset/image/arrow-down-decrease.svg
  - asset/image/arrow-down-increase.svg
  - asset/image/arrow-right.svg
  - asset/image/notification.svg
  - asset/image/pembayaranEwallet.svg
  - asset/image/pembayaranTransfer.svg
  - asset/image/pembayaranTunai.svg
  - asset/image/gallery-add.svg
  - asset/image/edit.svg
  - asset/image/info-circle.svg
  - asset/background/Wallet.svg
  - asset/setting/profile-2user.svg
  - asset/setting/percentage-circle.svg
  - asset/setting/message-question.svg
  - asset/setting/ticket-discount.svg
  - asset/setting/task-square.svg
  - asset/setting/shop.svg
  - asset/setting/security-safe.svg
  - asset/image/shopping-bag.svg
  - asset/kelolaOutlet/clarity_store-solid.svg
  - asset/kelolaOutlet/Frame.png
  - asset/kelolaOutlet/shop.svg
  - asset/kelolaOutlet/login.svg
  - asset/pegawai/Group 33979.svg
  - asset/promosi/shop.svg
  - asset/promosi/receipt-disscount.svg
  - asset/promosi/vuesaxoutlinecalendar.svg
  - asset/promosi/clock.svg
  - asset/setting/receipt-text.svg
  - asset/struk/play.svg
  - asset/settingAccount/logout.svg
  - asset/settingAccount/user-minus.svg
  - asset/settingAccount/user-remove.svg
  - asset/struk/printer.svg
  - asset/detailorder/bag-tick-2.svg
  - asset/detailorder/shop.svg
